export const crm_points = [
	{
		"crm_point_name" : "Welcome New Member",
		"crm_point_type_promotion": false,
		"crm_point_description" : "สำหรับลูกค้าที่ลงทะเบียนใหม่ รับ 100 Point",
		"crm_point_ratio_status" : false,
		"crm_point_ratio_point" : null,
		"crm_point_welcome_status" : true,
		"crm_point_welcome_point" : 100,
		"crm_point_percent_status" : false,
		"crm_point_percent_point" : null,
		"crm_point_percent_special_calcurate" : false,
		"crm_point_multiple_status" : false,
		"crm_point_multiple_point" : null,
		"crm_point_multiple_special_calcurate" : false,
		"crm_point_start_date" : "2022-09-26T23:55:42.294Z",
		"crm_point_end_date" : "2022-12-30T23:55:42.000Z",
		"status" : true,
		"createdAt" : "2022-09-26T23:56:36.404Z",
		"updatedAt" : "2022-09-26T23:58:22.790Z",
		"deleted" : false
	},
	{
		"crm_point_name" : "Default Points",
		"crm_point_type_promotion": false,
		"crm_point_description" : "ตั้งค่าการให้คะแนนปกติ",
		"crm_point_ratio_status" : true,
		"crm_point_ratio_point" : 25,
		"crm_point_welcome_status" : false,
		"crm_point_welcome_point" : null,
		"crm_point_percent_status" : false,
		"crm_point_percent_point" : null,
		"crm_point_percent_special_calcurate" : false,
		"crm_point_multiple_status" : false,
		"crm_point_multiple_point" : null,
		"crm_point_multiple_special_calcurate" : false,
		"crm_point_start_date" : "2022-09-26T23:55:42.000Z",
		"crm_point_end_date" : "2022-12-30T23:55:42.000Z",
		"status" : true,
		"createdAt" : "2022-09-26T23:57:16.366Z",
		"updatedAt" : "2022-09-27T00:10:12.165Z",
		"deleted" : false
	},
	{
		"crm_point_name" : "โปรโมชันคะแนน x2 สิ้นเดือน",
		"crm_point_type_promotion": true,
		"crm_point_description" : "ได้รับ point x2 ตั้งแต่วันนี้ถึงสิ้นเดือน September",
		"crm_point_ratio_status" : false,
		"crm_point_ratio_point" : null,
		"crm_point_welcome_status" : false,
		"crm_point_welcome_point" : null,
		"crm_point_percent_status" : false,
		"crm_point_percent_point" : null,
		"crm_point_percent_special_calcurate" : false,
		"crm_point_multiple_status" : true,
		"crm_point_multiple_point" : 2,
		"crm_point_multiple_special_calcurate" : true,
		"crm_point_start_date" : "2022-09-26T23:55:42.000Z",
		"crm_point_end_date" : "2022-12-30T23:55:42.000Z",
		"status" : true,
		"createdAt" : "2022-09-26T23:58:17.985Z",
		"updatedAt" : "2022-09-27T00:10:25.724Z",
		"deleted" : false
	}
]